### ISSUE TITLE
Question about nginx

### ISSUE THREAD

**Issue by aledbf** [jptosso/coraza-waf#10]
> nginx - > Coraza WAF -> Application

What are your plans with this integration?
Send NGINX traffic to a Coraza using a subrequest (njs or lua)?

**Comment by jptosso** [comment]
For now unix socket and http socket, for the next steps there should be a lua wrapper but I'm not sure if focusing on a Openresty module or a C++ wrapper for nginx using the future unix socket rpc interface. Anyway, both alternatives are possible with the current design.
RPC and Wrappers are going to be developed after the API is stable.
