### ISSUE TITLE
Failed to compile rule (Invalid variable URI_PARSER_ERROR)

### ISSUE THREAD

**Issue by sadicann** [jptosso/coraza-waf#108]
## Description

I tried to include OWASP CRS but I am getting this error. 
`{"level":"error","ts":1637334926.4698696,"msg":"[Parser] [Line 0] Failed to compile rule (Invalid variable URI_PARSER_ERROR): URI_PARSER_ERROR \"!@eq 0\" \"id:'200006', phase:1,t:none,log,deny,status:400,msg:'Failed to parse request url.',logdata:'Failed to parse request url',severity:2\"","line":0}
{"level":"error","ts":1637334926.4699538,"msg":"Invalid variable URI_PARSER_ERROR","path":"./rules/crs2.conf"}`

Config Lines:
```
SecRule URI_PARSER_ERROR "!@eq 0" \
"id:'200006', phase:1,t:none,log,deny,status:400,msg:'Failed to parse request url.',logdata:'Failed to parse request url',severity:2"
```

### Steps to reproduce
```
	waf := coraza.NewWaf()
	parser, _ := seclang.NewParser(waf)
	parser.FromFile("./rules/crs2.conf")
```
```
wget https://raw.githubusercontent.com/jptosso/coraza-waf/master/coraza.conf-recommended
git clone https://github.com/coreruleset/coreruleset
cat coraza.conf-recommended coreruleset/crs-setup.conf.example coreruleset/rules/*.conf > crs2.conf
```

**Comment by jptosso** [comment]
Hey @sadicann, I have removed this rule from the default config file, also please notice Coraza is migrating to v2, I suggest you try the beta version as core APIs are not going to change: https://github.com/jptosso/coraza-waf/releases/tag/v2.0.0-beta.1

There might still be issues with the CRS compatibility, please feel free to post any other issue and I will try to correct them. CRS compatibility is very important for this project.

**Comment by sadicann** [comment]
Is v2 ready to production with CRS ? I don't need all the rules of the CRS.

**Comment by jptosso** [comment]
v2 is closer to CRS than v1 but it requires you to import plugins into your project, for example, if you are doing this:

```go
import "github.com/jptosso/coraza-waf/v2"

...
waf := coraza.NewWaf()
```

You must update your code to:

```go
import(
"github.com/jptosso/coraza-waf/v2"
_ "github.com/jptosso/coraza-pcre"
_ "github.com/jptosso/coraza-libinjection"
)
```

It will provide support for libinjection and PCRE. In the next few weeks I will be releasing a special CRS fork that is fully compatible with coraza without plugins. Also I'm working on a libinjection implementation for GO without CGO: github.com/jptosso/libinjection-go

Coraza v2 is going through a lot of API changes for low level APIs, which means the core APIs like the transactions, parser and waf instances are not going to change.

**Comment by sadicann** [comment]
Thanks. I will try v2.
