### ISSUE TITLE
Question about Kubern8 Ingress Controller

### ISSUE THREAD

**Issue by aledbf** [jptosso/coraza-waf#11]
What's your plan about this?

I am the maintainer of [ingress-nginx](https://github.com/kubernetes/ingress-nginx) and one of the pain points is the WAF (ModSecurity) feature.
I'm always researching for alternatives that allow me to decouple the feature from the ingress controller and use a sidecar or maybe a socket (Shared Volume) in the same deployment?

**Comment by jptosso** [comment]
Hey Manuel, thank you for your interest.
I have been working in three solutions:

1. A unix socket RPC serving requests that holds transaction data in Redis with low latency
2. A C wrapper to invoke the WAF, but is hasn't been too effective, it's hard to export a golang software to C headers
3. A WAF rest API based on point 1

Once I achieve full compatibility with Skipper (contains ingress controller) and a stable API, these integrations will be the main focus.
