### ISSUE TITLE
Failed to compile rule using V2

### ISSUE THREAD

**Issue by 2969266** [jptosso/coraza-waf#138]
## Description

Failed to compile rule. No this error when I was using v1.2.0. 

After digging into the code I found that the latest code(V2) changed to use the "regexp" in GO SDK, however v1.2.0 uses "github.com/jptosso/coraza-waf/utils/regex" in file operators/rx.go.

### Steps to reproduce

Rule file: [REQUEST-920-PROTOCOL-ENFORCEMENT.txt](https://github.com/jptosso/coraza-waf/files/7806047/REQUEST-920-PROTOCOL-ENFORCEMENT.txt) 

### Expected result

No errors

### Actual result
INFO[0000] Initializing waf                             
FATA[0000] Failed to compile rule (error parsing regexp: invalid or unsupported Perl syntax: `(?<`): FILES_NAMES|FILES "@rx (?<!&(?:[aAoOuUyY]uml)|&(?:[aAeEiIoOuU]circ)|&(?:[eEiIoOuUyY]acute)|&(?:[aAeEiIoOuU]grave)|&(?:[cC]cedil)|&(?:[aAnNoO]tilde)|&(?:amp)|&(?:apos));|['\"=]" "id:920120,phase:2,block,t:none,t:urlDecodeUni,msg:'Attempted multipart/form-data bypass',logdata:'%{MATCHED_VAR}',tag:'application-multi',tag:'language-multi',tag:'platform-multi',tag:'attack-protocol',tag:'paranoia-level/1',tag:'OWASP_CRS',tag:'capec/1000/210/272',ver:'OWASP_CRS/3.3.0',severity:'CRITICAL',setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'"

**Comment by jptosso** [comment]
Hey, coraza v1 uses the ENV var CGO_ENABLED to pick between PCRE and RE2, please check CGO_ENABLED=1 is set before compiling, you will also need libpcre and libinjection.

I would suggest you migrate to v2, v1 is being deprecated, v2 is way faster, 100% compatible with CRS and receiving constant updates, it's getting a stable release in the next few days.

```sh
apt install libpcre++-dev -y

git clone https://github.com/libinjection/libinjection
gcc -std=c99 -Wall -Werror -fpic -c libinjection/src/libinjection_sqli.c -o libinjection/libinjection_sqli.o 
gcc -std=c99 -Wall -Werror -fpic -c libinjection/src/libinjection_xss.c -o libinjection/libinjection_xss.o
gcc -std=c99 -Wall -Werror -fpic -c libinjection/src/libinjection_html5.c -o libinjection/libinjection_html5.o
gcc -dynamiclib -shared -o libinjection/libinjection.so libinjection/libinjection_sqli.o libinjection/libinjection_xss.o libinjection/libinjection_html5.o
cp libinjection/*.so /usr/local/lib
cp libinjection/*.o /usr/local/lib
cp libinjection/src/*.h /usr/local/include/
chmod 444 /usr/local/include/libinjection*
ldconfig
```

**Comment by 2969266** [comment]
Using v2 I got below error, using V1 **NO** this error 

FATA[0000] Failed to compile rule (error parsing regexp: invalid or unsupported Perl syntax: (?<): FILES_NAMES|FILES "@rx (?<!&(?:[aAoOuUyY]uml)|&(?:[aAeEiIoOuU]circ)|&(?:[eEiIoOuUyY]acute)|&(?:[aAeEiIoOuU]grave)|&(?:[cC]cedil)|&(?:[aAnNoO]tilde)|&(?:amp)|&(?:apos));|['"=]" "id:920120,phase:2,block,t:none,t:urlDecodeUni,msg:'Attempted multipart/form-data bypass',logdata:'%{MATCHED_VAR}',tag:'application-multi',tag:'language-multi',tag:'platform-multi',tag:'attack-protocol',tag:'paranoia-level/1',tag:'OWASP_CRS',tag:'capec/1000/210/272',ver:'OWASP_CRS/3.3.0',severity:'CRITICAL',setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'"

**Comment by jptosso** [comment]
Using v2 you must import some plugins in order to support crs:

```go
import( 
 "github.com/jptosso/coraza-waf/v2"
 _ "github.com/jptosso/coraza-pcre" 
 _ "github.com/jptosso/coraza-libinjection" 
) 

```

Thats because cgo is not used by default on coraza v2

**Comment by 2969266** [comment]
It works after import the plugins.
