### ISSUE TITLE
Coraza benchmark

### ISSUE THREAD

**Issue by jiangrij** [jptosso/coraza-waf#143]
Will and when will Coraza benchmark be back? The repo https://github.com/jptosso/coraza-benchmark seems to be not existent, which is mentioned at https://coraza.io/docs/reference/benchmarks/.

Thanks.

**Comment by jptosso** [comment]
Thank you for your interest, I'm releasing today the new benchmark engine. I will keep you posted!

**Comment by jptosso** [comment]
I have created a few tests files, the results aren't ok I think something is wrong but I will figure it out. The benchmarks between Coraza WAF anc modsecurity con apache shows a difference of 30%~ but current tests are showing way more.

To compile it you will need libmodsecurity installed.

**Comment by jptosso** [comment]
Benchmarking repo is fully tested now. PCRE is going to be removed btw.
