### ISSUE TITLE
after ProcessResponseBody()  can not   return  all MatchedRules info

### ISSUE THREAD

**Issue by cts2021** [jptosso/coraza-waf#147]
Hi,jptosso.This is a very valuable project. Thanks for hardly working.I am currently learning about this project. I have some problems.

after ProcessResponseBody()  can not   return  all MatchedRules info .

### Steps to reproduce
     ... ...
	if tx.IsProcessableResponseBody() {
		tx.ResponseBodyBuffer.Write([]byte("#!/usr/bin/python"))
		tx.ProcessResponseBody()

		if it := tx.Interruption; it != nil {
			httpOutMsg := ""
			for _, res := range tx.MatchedRules {

				httpOutMsg = httpOutMsg + res.MatchedData.Key + ":" + res.MatchedData.Value + "\n"
				httpOutMsg = httpOutMsg + "Message:" + res.Message + "\n"

			}
                 fmt.Println(httpOutMsg)

### Expected result
deny and return all hit rules msg,should return the following rules

SecRule RESPONSE_BODY "@rx ^#\!\s?/" \
    "id:950140,\
    phase:4,\

### Actual result
 
deny ,but not return hit rules msg.

 looking forward to your help!

**Comment by jptosso** [comment]
Hey @cts2021, thank you very much for your feedback! I have reviewd your case and added a test to the seclang engine:

```go
func TestTXIssue147(t *testing.T) {
	// https://github.com/jptosso/coraza-waf/issues/147
	waf := coraza.NewWaf()
	parser, _ := NewParser(waf)
	err := parser.FromString(`SecRule RESPONSE_BODY "@rx ^#!\s?/" "id:950140,phase:4,log,deny,status:403"`)
	if err != nil {
		t.Error(err.Error())
	}
	tx := waf.NewTransaction()
	// response body access is required
	tx.ResponseBodyAccess = true
	// we need a content-type header
	tx.AddResponseHeader("Content-Type", "text/html")
	if tx.IsProcessableResponseBody() {
		if _, err := tx.ResponseBodyBuffer.Write([]byte("#!/usr/bin/python")); err != nil {
			t.Error(err)
		}
		it, err := tx.ProcessResponseBody()
		if err != nil {
			t.Error(err)
		}
		if it != nil {
			httpOutMsg := ""
			for _, res := range tx.MatchedRules {
				httpOutMsg = httpOutMsg + res.MatchedData.Key + ":" + res.MatchedData.Value + "\n"
				httpOutMsg = httpOutMsg + "Message:" + res.Message + "\n"

			}
			if len(httpOutMsg) == 0 {
				t.Error("failed to log")
			}
		} else {
			t.Error("failed to block response body")
		}
	} else {
		t.Error("failed to process response body")
	}
}
```

```sh
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestTXIssue147$ github.com/jptosso/coraza-waf/v2/seclang
ok  	github.com/jptosso/coraza-waf/v2/seclang	0.168s
```

Apparently you are missing the content-type header or ResponseBodyAccess.

Coraza rules for processing a requests are:

- The response body must match text/html, or text/plain, you may add more to ```waf.ResponseBodyMimeTypes``` or ```SecResponseBodyMimeType```.
- ```waf.RequestBodyAccess``` must be ```true```, you can set it using ```SecResponseBodyAccess On```

Please review the test and tell me if that fixes your issue.

Regards,

**Comment by cts2021** [comment]
thanks for your  response in time.

1 ,in coraza.conf file  already keep the setting:

SecRequestBodyAccess On
SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml

2. I check the Response header already   include "Content-Type,text/plain".

3.httpOutMsg  print:
 status:deny
hit rules count:1
ReqId:dIZNnIdQQluWIGJLLg2
host:192.168.101.36:8080
Message:Host header is a numeric IP address

4, the content of rule:
SecRule RESPONSE_BODY "@rx ^#\!\s?/" \
    "id:950140,\
    phase:4,\
    block,\
    capture,\
    t:none,\
    msg:'CGI source code leakage',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-disclosure',\
    tag:'paranoia-level/1',\
    tag:'OWASP_CRS',\
    tag:'capec/1000/118/116',\
    tag:'PCI/6.5.6',\
    ctl:auditLogParts=+E,\
    ver:'OWASP_CRS/3.3.2',\
    severity:'ERROR',\
    setvar:'tx.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}',\
    setvar:'tx.anomaly_score_pl1=+%{tx.error_anomaly_score}'"


 httpOutMsg    not include    " **msg:'CGI source code leakage',** "

**Comment by cts2021** [comment]
Core Rule Set   installed  by coraza  automatically  :)

**Comment by cts2021** [comment]
Hi,jptosso.
use： 
**parser.FromString**(`SecRule RESPONSE_BODY "@rx ^#!\s?/" "id:950140,phase:4,msg:'CGI source code leakage',log,deny,status:403"`)

httpOutMsg  can get  " msg:'CGI source code leakage', "

But  use  Core Rule Set  by  **parser.FromFile**("crs.conf") , get Message:Host header is a numeric IP address.

Regards,

**Comment by jptosso** [comment]
It still works, I think you have an issue with the CRS operation mode:

```
# Default: Anomaly Scoring mode, log to error log, log to ModSecurity audit log
# - By default, offending requests are blocked with an error 403 response.
# - To change the disruptive action, see RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
#   and review section 'Changing the Disruptive Action for Anomaly Mode'.
# - In Apache, you can use ErrorDocument to show a friendly error page or
#   perform a redirect: https://httpd.apache.org/docs/2.4/custom-error.html
#
SecDefaultAction "phase:1,log,auditlog,pass"
SecDefaultAction "phase:2,log,auditlog,pass"
```
Check your operation mode as if you are using a default ```deny```, it means any disruptive rules (```block```) that matches will stop the request and not evaluate any more rules, and if you use the anomaly scoring mode it means the only rule that will ```deny``` is the anomaly scoring rule at the end of phase 2.

**Comment by cts2021** [comment]
Yes,Core Rule Set  should be SecDefaultAction "phase:1,log,auditlog,pass".
thanks for your kindly help :)
